services:
  postgres:
    container_name: database
    env_file:
      - test.env
    ports:
      - '5431:5432'
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - truenas-sql:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - app-network
  server:
    container_name: server
    env_file:
      - test.env
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    ports:
      - '7999:8000'
    #command: bash -c "npx prisma migrate reset --force && npm run dev"
    command: bash -c "npm run dev"
    volumes:
      - ./server:/app
      - /app/node_modules
      - truenas-media:/app/media
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
  client:
    container_name: client
    env_file:
      - test.env
    build:
      context: ./client
      dockerfile: docker/Dockerfile.dev
    command: bash -c "npm run dev -- --host"
    ports:
      - '5172:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app-network
volumes:
  truenas-media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/aidensrocks/test/media
  truenas-sql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/aidensrocks/test/sql
networks:
  app-network:
    driver: bridge
