services:
  postgres:
    container_name: database
    ports:
      - '5431:5432'
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'OmegaA..1154'
      POSTGRES_DB: 'aidensrocks'
    volumes:
      - truenas-sql:/var/lib/postgresql/data
      - truenas-sql-backup:/backup
    networks:
      - app-network
    stop_grace_period: 60s
volumes:
  truenas-sql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/aidensrocks/test/sql
  truenas-sql-backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/aidensrocks/test/sql_backup
networks:
  app-network:
    driver: bridge
