services:
    postgres:
        container_name: database
        ports:
            - "5431:5432"
        image: postgres
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./docker_test_db:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
            interval: 5s
            timeout: 60s
            retries: 5
            start_period: 80s
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: docker/Dockerfile.dev
        ports:
            - "7999:8000"
        #command: bash -c "npx prisma migrate reset --force && npm run dev"
        command: bash -c "npm run dev"
        environment:
            DATABASE_URL: "${DATABASE_URL}"
            PORT: "${SERVER_PORT}"
        volumes:
            - ./server:/app
            - /app/node_modules
        depends_on:
            postgres:
                condition: service_healthy
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: docker/Dockerfile.dev
        command: bash -c "npm run dev -- --host"
        ports:
            - "5172:5173"
        volumes:
            - ./client:/app
            - /app/node_modules
        depends_on:
            - server
