services:
  postgres:
    container_name: database
    ports:
      - '5431:5432'
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - truenas-sql:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U $$DB_USER -d $$DB_NAME'"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - app-network
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: docker/Dockerfile.prod
    ports:
      - '7999:8000'
    #command: bash -c "npx prisma migrate reset --force && npm start"
    command: bash -c "npm start"
    volumes:
      - truenas-media:/app/media
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: docker/Dockerfile.prod
    command: bash -c "npm run preview"
    ports:
      - '4172:4173'
    depends_on:
      - server
    networks:
      - app-network
volumes:
  truenas-media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/aidensrocks/prod/media
  truenas-sql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/aidensrocks/prod/sql
networks:
  app-network:
    driver: bridge
