-- Regression-suite seed, loaded on top of data/sql/createdb.sql by
-- tests/setup/globalSetup.mjs. Keys are fixed so tests can refer to them;
-- sequences are bumped past them at the bottom. Every row exists to pin a
-- specific behaviour -- the comment says which. Media files for these rows
-- are generated by tests/helpers/media.mjs (writeSeedMedia).
--
-- All accounts share the password  Test-Passw0rd!  (bcrypt cost 4 for speed).

-- ---------- artists / catalog ----------
INSERT INTO artist (ra_key, display_name, relation) VALUES
  (1, 'Ashley', 'Mom'),
  (2, 'Grandpa Joe', NULL),          -- NULL relation must not null-out the artist label [S20]
  (3, 'Unused Artist', 'Friend');    -- deletable (no rocks)

INSERT INTO catalog (rc_key, rock_number, comment) VALUES
  (1, 101, 'Blue rock'),
  (2, 102, 'Green rock'),
  (3, 103, 'Hidden-journey rock'),
  (4, 104, 'Rock with no artist');   -- editing it must not send ra_key NULL [A7]

INSERT INTO artist_link (ral_key, ra_key, rc_key) VALUES
  (1, 1, 1),
  (2, 2, 2),
  (3, 1, 3);

-- ---------- journeys ----------
-- Rock 101: two visible stops, oldest first by date. The API returns newest
-- first, so the client must not treat element 0 as the start date [C1].
INSERT INTO journey (rps_key, rock_qr_number, rock_number, location, date, comment, name, email,
                     uuid, show, latitude, longitude, country, state, create_dt) VALUES
  (1, 101, 101, 'Hocking Hills, OH', '2025-06-01', 'First stop',  'Finder One', 'finder1@example.com',
   '11111111-1111-4111-8111-111111111111', true, 39.4359, -82.5390, 'United States', 'Ohio', '2025-06-01'),
  (2, 101, 101, 'Zion, UT',          '2025-08-01', 'Second stop', 'Finder Two', 'finder2@example.com',
   '22222222-2222-4222-8222-222222222222', true, 37.2982, -113.0263, 'United States', 'Utah', '2025-08-01'),
-- Rock 102: visible, but no coordinates yet (uploads don't geocode) [C1 NaN distance]
  (3, 102, 102, 'Somewhere',         '2025-07-01', 'No coords',   'Finder Three', NULL,
   '33333333-3333-4333-8333-333333333333', true, NULL, NULL, 'United States', NULL, '2025-07-01'),
-- Rock 103: hidden stop -- must not appear or be counted anywhere public [C-stats]
  (4, 103, 103, 'Secret, HI',        '2025-07-15', 'Hidden',      'Finder Four', 'finder4@example.com',
   '44444444-4444-4444-8444-444444444444', false, 21.3069, -157.8583, 'United States', 'Hawaii', '2025-07-15'),
-- Rock 104: visible stop with zero visible images -- must be treated the
-- same by the list, the count and the map pin [C3 / C-pin]
  (5, 104, 104, 'Imageless',         '2025-07-20', 'No images',   'Finder Five', NULL,
   '55555555-5555-4555-8555-555555555555', true, 40.0, -83.0, 'Canada', NULL, '2025-07-20');

INSERT INTO journey_image (rpi_key, rps_key, original_name, current_name, upload_order, show, width, height) VALUES
  (1, 1, 'a.jpg', '11111111-1111-4111-8111-111111111111_1', 1, true, 64, 48),
  (2, 2, 'b.jpg', '22222222-2222-4222-8222-222222222222_1', 1, true, 64, 48),
  (3, 3, 'c.jpg', '33333333-3333-4333-8333-333333333333_1', 1, true, 64, 48),
  (4, 4, 'd.jpg', '44444444-4444-4444-8444-444444444444_1', 1, true, 64, 48),
  (5, 5, 'e.jpg', '55555555-5555-4555-8555-555555555555_1', 1, false, 64, 48);

-- ---------- photo albums / music ----------
INSERT INTO photoalbums (pa_key, name, display_name, "desc", order_num, show) VALUES
  (1, 'visible-album', 'Visible Album', 'Shown', 1, true),
  (2, 'hidden-album',  'Hidden Album',  'Hidden', 2, false);   -- not public [S16]
INSERT INTO photoalbum_tags (pa_key, tag) VALUES (1, 'main');

INSERT INTO photos (p_key, pa_key, name, display_name, date, order_num, show, width, height) VALUES
  (1, 1, 'p1.webp', 'Shown photo',  '2025-05-01', 1, true, 64, 48),
  (2, 1, 'p2.webp', 'Hidden photo', '2025-05-02', 2, false, 64, 48);   -- not public [S16]

INSERT INTO music (m_key, name, writer, lyrics, order_num, show) VALUES
  (1, 'Visible Song', 'Writer', 'la la', 1, true),
  (2, 'Hidden Song',  'Writer', 'shh',   2, false);   -- not public [S16]

-- ---------- Honoring Aiden ----------
INSERT INTO entry (id, slug, title, sort_order, published, body_json) VALUES
  (1, 'about-aiden', 'About Aiden', 1, true,
   '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Aiden loved rocks."}]}]}'),
  (2, 'draft-entry', 'Draft Entry', 2, false,
   '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Not yet."}]}]}');

-- ---------- rock requests ----------
INSERT INTO rock_requests (rq_key, name, email, address, rocks_requested, message) VALUES
  (1, 'Requester', 'requester@example.com', '1 Main St', 2, 'Please send rocks');

-- ---------- accounts ----------
INSERT INTO account (id, email, first_name, last_name, password_hash, access_level, email_verified_dt, is_locked) VALUES
  (1, 'admin@example.com',      'Ada',  'Admin',     '$2b$04$cMXoPyLd1RzERZDcedWzkujVAtNNIMlQs4.fQs./ZosRX0h4Z6EIq', 50, NOW(), false),
  (2, 'user@example.com',       'Uma',  'User',      '$2b$04$cMXoPyLd1RzERZDcedWzkujVAtNNIMlQs4.fQs./ZosRX0h4Z6EIq', 20, NOW(), false),
  (3, 'creator@example.com',    'Cree', 'Creator',   '$2b$04$cMXoPyLd1RzERZDcedWzkujVAtNNIMlQs4.fQs./ZosRX0h4Z6EIq', 30, NOW(), false),
  (4, 'unverified@example.com', 'Una',  'Verified',  '$2b$04$cMXoPyLd1RzERZDcedWzkujVAtNNIMlQs4.fQs./ZosRX0h4Z6EIq', 10, NULL,  false),
  (5, 'locked@example.com',     'Lou',  'Locked',    '$2b$04$cMXoPyLd1RzERZDcedWzkujVAtNNIMlQs4.fQs./ZosRX0h4Z6EIq', 20, NOW(), true);

-- ---------- sequences past the fixed keys ----------
SELECT setval('artist_ra_key_seq', 100);
SELECT setval('artist_link_ral_key_seq', 100);
SELECT setval('catalog_rc_key_seq', 100);
SELECT setval('journey_rps_key_seq', 100);
SELECT setval('journey_image_rpi_key_seq', 100);
SELECT setval('photoalbums_pa_key_seq', 100);
SELECT setval('photos_p_key_seq', 100);
SELECT setval('music_m_key_seq', 100);
SELECT setval('entry_id_seq', 100);
SELECT setval('rock_requests_rq_key_seq', 100);
SELECT setval('account_id_seq', 100);
