FROM node:18
ARG VITE_API_URL=http://192.168.1.40:7999
ENV VITE_API_URL=$VITE_API_URL
WORKDIR /client
COPY public/ /client/public
COPY src/ /client/src
COPY index.html /client/
COPY package.json /client/
COPY vite.config.js /client/
RUN npm install
RUN npm run build