FROM node:18
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
WORKDIR /app
COPY public/ /app/public
COPY src/ /app/src
COPY index.html /app/
COPY package.json /app/
COPY vite.config.js /app/
RUN npm install
RUN npm run build